spring.datasource.url=jdbc:postgresql://ep-tiny-pond-a1493adj-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_SG0yzZgCXwY8
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8081

# Aviationstack API Integration
aviationstack.key=91750997d884945ab2c8627d835f0d04
aviationstack.base-url=http://api.aviationstack.com/v1/flights